# Form implementation generated from reading ui file 'd:\Onedrive\CodeS\Python\YeXiao\DataToTab_ReSplitDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_ReSplit = QtWidgets.QPushButton(parent=Dialog)
        self.btn_ReSplit.setObjectName("btn_ReSplit")
        self.gridLayout.addWidget(self.btn_ReSplit, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.btn_Confirm = QtWidgets.QPushButton(parent=Dialog)
        self.btn_Confirm.setObjectName("btn_Confirm")
        self.gridLayout.addWidget(self.btn_Confirm, 0, 3, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_ReSplit.setText(_translate("Dialog", "重新拆分"))
        self.label.setText(_translate("Dialog", "分隔符："))
        self.btn_Confirm.setText(_translate("Dialog", "确定导入"))
